apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: rbmh-berglas-webhook
  labels:
    app: rbmh-berglas-webhook
    kind: mutator

webhooks:
- name: rbmh-berglas-webhook.cloud.google.com
  clientConfig:
    url: REPLACE_WITH_YOUR_URL
    caBundle: ""
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods","jobs"]
